policies:
  - tool_pattern: "db_*"
    rules:
      - type: sql_safety
        block_keywords:
          - DROP
          - DELETE
          - TRUNCATE
          - ALTER
        allow_with_confirmation: true
        
  - tool_pattern: "shell_*"
    rules:
      - type: command_safety
        block_commands:
          - rm -rf
          - mkfs
          - dd
        require_approval: true
        
  - tool_pattern: "*"
    rules:
      - type: secret_redaction
        patterns:
          - api[_-]?key
          - password
          - token
          - secret
          
  - tool_pattern: "*"
    rules:
      - type: rate_limit
        calls_per_minute: 60
        calls_per_hour: 1000
